name: Build and Deploy Landing + Blog

on:
  workflow_call:
    inputs:
      channel_id:
        required: true
        type: string
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: cd website && npm ci

      - name: Build Astro site
        run: npm run
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: "${{ inputs.channel_id }}"
          projectId: praxio-app
