name: Deploy website to Firebase dedicated channel on PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    uses: ./.github/workflows/build-and-deploy-common.yml
    with:
      channel_id: pr-${{ github.event.number }}
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}
