name: Deploy landing page and blog to Firebase live channel on pull request

on:
  pull_request:
    branches:
      - main

permissions:
  deployments: write
  pull-requests: write

jobs:
  build_and_deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      channel_id: pr-${{ github.event.number }}
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}
