name: Build and Deploy Landing + Blog

on:
  workflow_call:
    inputs:
      channel_id:
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo site
        run: cd blog && hugo --minify

      - name: Prepare files for deployment
        run: |
          # Create the directory where we'll merge the blog and landing build
          mkdir -p build/public/blog

          # Copy landing page files (Assumes landing page is already ready in the landing folder)
          cp -r landing/* build/public/

          # Copy blog files to the /blog path
          cp -r blog/public/* build/public/blog/

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}"
          channelId: ${{ inputs.channel_id }}
          projectId: praxio-app
