name: Deploy Hugo Blog to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: |
          cd blog
          hugo --minify

      - name: Prepare files for deployment
        run: |
          # Create the directory where we'll merge the blog and landing build
          mkdir -p firebase-public/blog
          
          # Copy landing page files (Assumes landing page is already ready in the landing folder)
          cp -r landing/* firebase-public/
          
          # Copy blog files to the /blog path
          cp -r blog/public/* firebase-public/blog/

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}'
          channelId: live
          projectId: praxio-app
          public: firebase-public