name: Deploy landing page and blog to Firebase live channel on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      channel_id: live
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}
