name: Deploy landing page and blog to Firebase live channel on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/deploy.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAXIO_APP }}"
          channelId: live
          projectId: praxio-app
